FROM openjdk:17-jdk-slim AS build

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package

FROM openjdk:17-jdk-slim
WORKDIR smartcontacts
COPY --from=build target/smartcontacts-0.0.1-SNAPSHOT.jar smartcontacts.jar
ENTRYPOINT ["java", "-jar", "smartcontacts.jar"]